import React, { useState } from 'react';
import { WaterBody } from '../types';
import {
  FileText,
  Download,
  Calendar,
  Layers,
  CheckCircle2,
  Printer,
  Sparkles,
  ShieldCheck,
} from 'lucide-react';

interface ReportsViewProps {
  waterBodies: WaterBody[];
  selectedWaterBody: WaterBody;
}

export const ReportsView: React.FC<ReportsViewProps> = ({
  waterBodies,
  selectedWaterBody,
}) => {
  const [reportType, setReportType] = useState('executive');
  const [dateRange, setDateRange] = useState('30d');
  const [isExporting, setIsExporting] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const handleDownload = () => {
    setIsExporting(true);
    setTimeout(() => {
      setIsExporting(false);
      setDownloadSuccess(true);

      // Create a downloadable formatted research summary
      const reportText = `
========================================================================
AQUA INTELLIGENCE: AUTONOMOUS WATER INTELLIGENCE & DECISION SUPPORT SYSTEM
OFFICIAL ENVIRONMENTAL MONITORING & RISK ASSESSMENT REPORT
Generated: ${new Date().toISOString()}
Target Catchment: ${selectedWaterBody.name} (${selectedWaterBody.location})
Status: ${selectedWaterBody.qualityStatus.toUpperCase()}
========================================================================

1. PHYSICOCHEMICAL SENSOR SUMMARY:
- pH Level: ${selectedWaterBody.parameters.pH} (Nominal: 6.5 - 8.5)
- Turbidity: ${selectedWaterBody.parameters.turbidity} NTU
- Total Dissolved Solids: ${selectedWaterBody.parameters.tds} ppm
- Water Temperature: ${selectedWaterBody.parameters.temperature} °C
- Dissolved Oxygen: ${selectedWaterBody.parameters.dissolvedOxygen} mg/L

2. COMPUTER VISION OPTICAL OBSERVATIONS:
- Floating Debris Count: ${selectedWaterBody.wasteObjectsCount} units
- Detection Architecture: YOLOv8 WaterVision Edge
- Model Consensus Confidence: ${selectedWaterBody.aiConfidence}%

3. DECISION SUPPORT & ACTION PLAN:
- Normalized Risk Score: ${selectedWaterBody.riskScore} / 100
- Recommended Action: "${selectedWaterBody.recommendedAction}"

DISCLAIMER:
This document is generated by an academic environmental decision-support system.
Data reflects telemetry samples and requires verified wet-lab confirmation for potability.
========================================================================
      `.trim();

      const blob = new Blob([reportText], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `AquaIntelligence_Report_${selectedWaterBody.id}_${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setTimeout(() => setDownloadSuccess(false), 3000);
    }, 700);
  };

  return (
    <div className="space-y-6 animate-in fade-in pb-12">
      {/* Header */}
      <div className="p-5 rounded-2xl bg-[#09263A]/80 border border-[#0B5E75]/40 backdrop-blur-md flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-[#28D7D7]" />
            <h2 className="text-xl font-bold text-white tracking-wide">
              Environmental Intelligence Reports & Audits
            </h2>
          </div>
          <p className="text-xs text-slate-300 mt-1">
            Export comprehensive regulatory dossiers, executive summaries, and raw telemetry datasets
          </p>
        </div>

        <button
          onClick={handleDownload}
          disabled={isExporting}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-[#13A8A8] to-[#0B5E75] hover:from-[#28D7D7] hover:to-[#13A8A8] hover:text-[#061826] text-white font-bold text-xs transition-all shadow-lg shadow-[#13A8A8]/20 disabled:opacity-50"
        >
          <Download className="w-4 h-4" />
          <span>{isExporting ? 'Compiling Dossier...' : 'Export Formal Dossier'}</span>
        </button>
      </div>

      {downloadSuccess && (
        <div className="p-3 rounded-xl bg-emerald-950/60 border border-emerald-800/50 text-emerald-400 text-xs flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4" />
          <span>Report exported successfully to your downloads directory!</span>
        </div>
      )}

      {/* Report Configuration and Live Preview */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Controls */}
        <div className="lg:col-span-4 rounded-3xl bg-[#09263A]/85 border border-[#0B5E75]/40 p-6 backdrop-blur-md shadow-xl space-y-4">
          <span className="text-xs font-mono font-bold text-[#28D7D7] uppercase tracking-wider block">
            Dossier Scope & Parameters
          </span>

          <div className="space-y-3 text-xs">
            <div>
              <label className="block text-slate-300 font-semibold mb-1">Report Archetype</label>
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-[#061826] border border-[#0B5E75] text-white focus:outline-none focus:border-[#13A8A8]"
              >
                <option value="executive">Executive Decision Support Brief</option>
                <option value="technical">Physicochemical Laboratory Audit</option>
                <option value="cv-waste">Optical Debris Computer Vision Log</option>
              </select>
            </div>

            <div>
              <label className="block text-slate-300 font-semibold mb-1">Observation Interval</label>
              <select
                value={dateRange}
                onChange={(e) => setDateRange(e.target.value)}
                className="w-full px-3 py-2 rounded-xl bg-[#061826] border border-[#0B5E75] text-white focus:outline-none focus:border-[#13A8A8]"
              >
                <option value="24h">Last 24 Hours (Real-time)</option>
                <option value="7d">Last 7 Days (Short Trend)</option>
                <option value="30d">Last 30 Days (Monthly Baseline)</option>
                <option value="6m">Last 6 Months (Longitudinal)</option>
              </select>
            </div>
          </div>

          <div className="p-3 rounded-xl bg-[#061826] border border-[#0B5E75]/30 text-[11px] text-slate-400 space-y-1">
            <span className="font-bold text-white block">Audit Sign-Off</span>
            <span>Generated under ISO-14044 Environmental Management & Automated Decision Guidelines</span>
          </div>
        </div>

        {/* Live Document Preview */}
        <div className="lg:col-span-8 rounded-3xl bg-[#061826]/95 border border-[#0B5E75]/50 p-6 backdrop-blur-xl shadow-2xl font-mono text-xs text-slate-300 space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-[#0B5E75]/40 text-[#28D7D7]">
            <span className="font-bold">AQUA_INTELLIGENCE_REPORT.DOSS</span>
            <span>PAGE 1 OF 1</span>
          </div>

          <div className="space-y-2">
            <div className="text-white font-extrabold text-sm uppercase">
              Catchment Ecosystem Audit: {selectedWaterBody.name}
            </div>
            <div className="text-slate-400">
              Station Location: {selectedWaterBody.location} • Area: {selectedWaterBody.areaSqKm} km²
            </div>
          </div>

          <div className="p-4 rounded-xl bg-[#09263A]/70 border border-[#0B5E75]/40 space-y-2">
            <span className="text-white font-bold block">1. EXECUTIVE SUMMARY</span>
            <p className="leading-relaxed text-slate-300">
              During the analyzed monitoring window, {selectedWaterBody.name} demonstrated a composite risk index of{' '}
              <strong className="text-amber-400">{selectedWaterBody.riskScore}/100</strong> ({selectedWaterBody.qualityStatus.toUpperCase()}). Sonde array telemetry confirms turbidity elevation ({selectedWaterBody.parameters.turbidity} NTU) and {selectedWaterBody.wasteObjectsCount} optical floating waste debris units detected via YOLOv8 inference.
            </p>
          </div>

          <div className="p-4 rounded-xl bg-[#09263A]/70 border border-[#0B5E75]/40 space-y-2">
            <span className="text-white font-bold block">2. DECISION SUPPORT DIRECTIVE</span>
            <p className="leading-relaxed text-slate-300">
              Action Plan: "{selectedWaterBody.recommendedAction}"
            </p>
          </div>

          <div className="pt-2 text-[10px] text-slate-500 border-t border-[#0B5E75]/30">
            CONFIDENTIAL ENVIRONMENTAL DOCUMENT • AQUA INTELLIGENCE DECISION SUPPORT
          </div>
        </div>
      </div>
    </div>
  );
};
